name: Alan Crowe
favicon: null
layout_spectrum: 0.31274429545737803
typography_spectrum: 0.022847407963126898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4865233183372766
  lightness: 0.026087606325745583
  saturation: 0.6456157001666725
  rhythmicContrast: 0.3232980705797672
purpose: []
